### ISSUE TITLE
Update man pages?

### ISSUE THREAD

**Issue by musicinmybrain** [libsndfile/sndfile-tools#77]
The man pages currently provide less information than the `--help` output, and there is no man page for `sndfile-waveform`.

Is there any interest in updating the man pages to match the level of detail in the `--help` output of the various commands?

If not, would the answer change if I offered a PR to do so?

**Comment by evpobr** [comment]
We are not one of those who refuse help. :smile:

**Comment by janstary** [comment]
This has been merged years ago, so the ticket can be closed, right?
